# Generated by Django 5.0 on 2023-12-13 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='pickup_choice',
            new_name='pickup_type',
        ),
        migrations.AddField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
