# Generated by Django 5.0 on 2023-12-13 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_rename_pickup_choice_checkout_pickup_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
