# Generated by Django 5.0 on 2023-12-17 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_alter_checkout_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
