# Generated by Django 5.0 on 2023-12-21 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0007_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 3, 19, 9, 130368, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickup',
            name='pickup_time',
            field=models.DateTimeField(default=()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='area',
            field=models.CharField(choices=[('kabwata', 'matero'), ('chelstone', 'kalingalinga')], max_length=255),
        ),
    ]
